language: python
python:
  - "3.8"
sudo: required
services:
  - docker
env:
  - DOCKER_COMPOSE_VERSION=3.8
before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
before_script:
  - docker-compose up -d --build
  - docker exec -it django_web pip install -r requirements/test.txt
script:
  - docker exec -it django_web pytest --cov
  - docker exec -it django_web pre-commit run --all-files
after_script:
  - docker-compose down
#deploy:
#  provider: elasticbeanstalk
#  access_key_id: $ACCESSKEYID
#  secret_access_key: $SECRETACCESSKEY
#  region: "us-east-1"
#  app: "django-tutorial"
#  env: "django-env"
#  bucket_name: "elasticbeanstalk-us-east-1-017801987097"
#  on:
#    branch: master
#after_deploy:
#  - sudo bash after_deploy.sh