version: '3.8'
services:
  web:
    container_name: django_web
    build: ./
    command: ./bin/run_django_app_dev.sh
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.test
    depends_on:
      - db
  db:
    container_name: postgres_db
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.test.db
  celery:
    container_name: celery
    build: ./
    command: ./bin/run_celery.sh
    volumes:
      - ./:/usr/src/app/
    env_file:
      - ./.env.test
    depends_on:
      - web
      - db
      - redis
  redis:
    container_name: redis
    image: redis:alpine
    restart: always
volumes:
  postgres_data:
