version: '3.8'
services:
  web:
    container_name: django_web
    build:
      context: ./
      dockerfile: Dockerfile.prod
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/media
    command: ./bin/run_django_app_prod.sh
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    container_name: postgres_db
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  celery:
    container_name: celery
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: ./bin/run_celery.sh
    volumes:
      - ./:/home/app/web/
    env_file:
      - ./.env.prod
    depends_on:
      - web
      - db
      - redis
  redis:
    container_name: redis
    image: redis:alpine
    restart: always
  nginx:
    container_name: nginx
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/media
    ports:
      - 80:80
    depends_on:
      - web
volumes:
  postgres_data:
  static_volume:
  media_volume: