[tool.black]
line_length = 80
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
line_length = 80
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 2
use_parentheses = true
ensure_newline_before_comments = true
default_section = "THIRDPARTY"
known_third_party = ["captcha", "celery", "django", "factory", "faker", "pytest", "pytest_factoryboy", "rest_framework", "storages"]
known_first_party = ["cinema", "accounts", "api"]

[tool.pylint.MESSAGE_CONTROL]
disable="""
bad-continuation,
no-else-return,
too-few-public-methods,
line-too-long,
duplicate-code,
import-error,
unused-argument,
no-self-use,
import-outside-toplevel,
fixme,
missing-module-docstring,
missing-class-docstring,
missing-function-docstring,
invalid-str-returned,
no-member,
"""
[tool.pylint.REPORTS]
reports="no"
[tool.pylint.FORMAT]
max-line-length="80"
[tool.pylint.BASIC]
good-names="_,i,j,k,e,q,qs,pk,setUp,tearDown,maxDiff,default_app_config"
